resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: glue-viz
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    xvfb: true
    coverage: codecov
    libraries:
      apt:
        - libxkbcommon-x11-0

    envs:

    - linux: codestyle
      libraries: {}
      coverage: 'false'

    - linux: py36-test
    - linux: py37-test
    - linux: py38-test-dev
    - linux: py39-test-dev

    - macos: py36-test
    - macos: py37-test
    - macos: py38-test-dev
    - macos: py39-test-dev

    # We don't test on Windows since there are no rasterio wheels
    # available there, but there's no reason in principle why the
    # plugin code here should be platform dependent.